### ISSUE TITLE
Database Timezone ommission

### ISSUE THREAD

**Issue by scottnotscott** [krgamestudios/MERN-template#16]
## Suggestion: 

Remove DB_TIMEZONE requirement from dotenv requirements OR provide handy list of available localisation snippets of appropriate values.

&

## DB_LOGGING=true

OPTIONAL: setting this option in your dotenv will provide logging of SQL statements made to the console. Helpful for bug fixing and development.

Thank you!

**Comment by Ratstail91** [comment]
Each microservice (and the core) now have references to this page:

https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

This page contains a list of all valid time zones - though they haven't all been fully tested. 

I've also added `DB_LOGGING=` as an option as well.
